[env:node_a_sensor]
platform     = https://github.com/pioarduino/platform-espressif32/releases/download/53.03.13/platform-espressif32.zip
board        = seeed_xiao_esp32c6
framework    = arduino
monitor_speed  = 115200
upload_speed   = 921600
monitor_filters = esp32_exception_decoder

board_build.filesystem  = littlefs
board_build.partitions  = partitions.csv

lib_deps =
    bblanchon/ArduinoJson@^7.0.0
    knolleary/PubSubClient@^2.8
    h2zero/NimBLE-Arduino@^2.0.0
    ESP32Async/ESPAsyncWebServer@^3.4.0
    ESP32Async/AsyncTCP@^3.4.0
    ayushsharma82/ElegantOTA@^3.1.5

build_flags =
    -DCORE_DEBUG_LEVEL=3
    -DCONFIG_ARDUINO_LOOP_STACK_SIZE=8192
    -DARDUINO_USB_MODE=1
    -DELEGANTOTA_USE_ASYNC_WEBSERVER=1
